[pytest]
addopts = --html-report=./report

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    smoke: בדיקות sanity מהירות לתפקוד בסיסי
    regression: חבילת regression מלאה
    negative: תרחישי שגיאה וקלט לא תקין
    e2e: זרימות end-to-end מלאות
    performance: בדיקות ביצועים וזמני תגובה