name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t api-testing .

      - name: Run tests in Docker
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          REQRES_URL: ${{ secrets.REQRES_URL }}
        run: |
          docker run --rm \
            -e REQRES_API_KEY=${{ secrets.REQRES_API_KEY }} \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -e REQRES_URL=${{ secrets.REQRES_URL }} \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            api-testing \
            pytest tests/ -v --alluredir=allure-results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/